version: "3.8"

services:

  attacker_router:
    image: openwrtorg/rootfs
    ports:
      - "14561:80"
    networks:
      attacker_net:
        ipv4_address: 172.20.1.3
      victim_net:
        ipv4_address: 172.20.2.3
    # command: ash -c "mkdir -p /var/lock && opkg update && opkg install uhttpd && opkg update && opkg install luci"


  attacker:
    build:
      context: ./busybox
      dockerfile: dockerfile 
    cap_add:
      - ALL
    environment:
      - DEFAULT_IP=172.20.1.1
      - GATEWAY_IP=172.20.1.3
    stdin_open: true
    tty: true
    networks:
      - attacker_net

  victim:
    build:
      context: ./busybox
      dockerfile: dockerfile 
    cap_add:
      - ALL
    environment:
      - DEFAULT_IP=172.20.2.1
      - GATEWAY_IP=172.20.2.3
    stdin_open: true
    tty: true
    networks:
      - victim_net

networks:
  attacker_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24

  victim_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.2.0/24

