filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  
processors:
  - convert:
      fields:
        - {from: "num", to: "packet", type: "integer"}
        - {from: "source", to: "source.ip", type: "ip"}
        - {from: "destination", to: "destination.ip", type: "ip"}
        - {from: "spoofed", to: "spoofed", type: "boolean"}
      ignore_missing: true
      fail_on_error: false

# service name of elastic search container
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

filebeat.inputs:
- type: log
  paths:
    - /var/log/zeek_logs/egress.log
  json.keys_under_root: true
  #json.add_error_key: true

