filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# pass as enviroment variable
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

filebeat.inputs:
- type: log
  paths:
    - /var/log/zeek_logs/*.log
